config/routes.rb
Appheradashboard::Application.routes.draw do
  resources :folders

  resources :types

  resources :items

  resources :customers
  resources :provider_slugs

  post 'accounts/payment'
  match 'purchases/new' => "purchases#new"
  match 'purchases/create' => "purchases#create"

  resources :listings
  resources :plans

  resources :subscriptions do
    collection do
      post :change_plan
    end
  end



  resources :contacts

  match 'resellers/setscope' => 'resellers#setscope', :as => :setscope
  match 'page/network' => 'pages#network'
  resources :resellers
  root :to => 'home#index'


  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "omniauth_callbacks",  :passwords => 'passwords'} do
    get '/users/auth/:provider' => 'omniauth_callbacks#twitter'
  end
    get '/home/city_autocomplete'
  resources :home
  resources :users
  resources :reports
  
  # from old dashboard
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sentiments
      resources :keywords
      resources :organizations
      resources :uptime_monitors
    end
  end
  
  # resources :pages do
  #     member { post :mercury_update }
  #   end
 
 # ActiveAdmin.routes(self)
 
 # scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
  #devise_for :admin_users, ActiveAdmin::Devise.config, ActiveAdmin::Devise.config
  
  
  resources :ProxiesApi
  

  resources :start

  resources :reviewers

  resources :accounts do
    collection do
      post :update_credit_card
    end
  end

  resources :rankings

  resources :keywords
  
  resources :misc

 # match 'new_organizations/new' => 'new_organizations/new'
  match 'reviews/test' => 'reviews#index2'
  match 'reviewers2/test' => 'reviewers#index2'
  
  

  resources :reviews

  resources :aggregate_results
  
 # match 'organizations/unlink' => 'organizations#unlink'
  match 'organizations/myorgs' => 'organizations#myorgs'
  match 'organizations/mapview' => 'organizations#mapview'

  resources :organizations do
    collection do
      get :autocomplete_city
      post :autocomplete_categories
    end
  end

  resources :recommendations
  resources :uptime_monitors
  resources :my_competitors

  resources :history_items

  #match 'api/organizations' => 'api#organizations'
 
  # namespace :reseller do
  #     resources :accounts
  #     resources :organizations
  #   end
  
  
  
end

app/models/aggregate_result.rb
class AggregateResult < ActiveRecord::Base
  belongs_to :organization

  store :competitor_results, accessors: [:cscore, :creviews, :creview_average, :cnegative_reviews, :cnegative_reviews_new, :cneutral_reviews, :cneutral_reviews_new, :cvideos, :cphotos, :ctweets, :ctweets_new, :cfb_likes, :cfb_likes_new, :cscore, :cfollowers, :cfollowing]


end

app/controllers/aggregate_results_controller.rb
class AggregateResultsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_org
  caches_page :index

  # GET /aggregate_results
  # GET /aggregate_results.json
  def index
    unless @org
      redirect_to new_account_path, :notice => 'Bitte fuegen Sie eine Niederlassung oder Filiale hinzu.' and return
    end

    org = @org
    org = current_user.account.organizations.first unless @org

    #Resque.enqueue(Aggregate,org.id)

    begin
      @aggregate_result = org.aggregate_results.last
      @aggregate_results2 = []
    rescue
    end
    begin
      comps = org.organizations(:include => [:organizations])
    rescue
    end

    unless comps.nil?
      comps.each do |c|
        begin
          res = c.aggregate_results.last
          if res.reviews != 0
            @aggregate_results2 << res
          end
        rescue
        end
      end
      @avg_rating = 0

      @aggregate_count = @aggregate_results2.count
      @aggregate_results2.each do |a|
        begin

          @avg_rating += a.review_avg/@aggregate_count
        rescue

        end
      end
      @avg_rating = sprintf("%.2f", @avg_rating)
      # unless @aggregate_result.nil?
      #         @h = LazyHighCharts::HighChart.new('graph') do |f|
      #           f.options[:legend][:align] = "right"
      #           f.options[:chart][:defaultSeriesType] = "column"
      #           f.options[:title][:text] = "Review Trend"
      #           f.options[:xAxis][:categories] = ["Review Bewertungen"]
      #           f.series(:name => 'Mein Unternehmen', :data => [@aggregate_result.review_avg])
      #           @aggregate_results2.each do |agg|
      #             f.series(:name => agg.organization.name, :data => [agg.review_avg])
      #           end
      #         end


      #end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aggregate_results }
    end
  end

  # GET /aggregate_results/1
  # GET /aggregate_results/1.json
  def show
    @aggregate_result = AggregateResult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aggregate_result }
    end
  end

  # GET /aggregate_results/new
  # GET /aggregate_results/new.json


  # PUT /aggregate_results/1
  # PUT /aggregate_results/1.json

end

app/views/aggregate_results/index.html.erb
<div id="masthead">

  <div class="container">

    <div class="masthead-pad">

      <div class="masthead-text">
        <h2><%= t(:overview) %></h2>


      </div>
      <!-- /.masthead-text -->

    </div>

  </div>
  <!-- /.container -->

</div> <!-- /#masthead -->




<div id="content">

  <div class="container">


    <div class="row">

      <div class="span12">


        <h3><%= t(:average_of_all_competitors) %> :<%= @avg_rating.to_s %></h3>
        <% unless @aggregate_result.nil? %>
            <h3><%= t(:your_review_average) %> :<%= @aggregate_result.review_avg %></h3>
        <% end %>

        <% unless @aggregate_results2.nil? %>
            <div id="vertical-chart" class="chart-holder"></div>
            <div id="chart-legend"></div>
            <script type="text/javascript">
                var data = [];

                <% @aggregate_results2.each_with_index do |ar, i| %>
                data.push({
                    data:[
                        [<%= i %>, <%= ar.review_avg %>]
                    ],
                    label:'<%= ar.organization.name %>',
                    bars:{
                        show:true,
                        barWidth:0.5,
                        align:'center'
                    }
                });
                <% end %>

                Charts.vertical('#vertical-chart', data);
            </script>
        <% end %>

        <table class="table table-striped table-bordered table-highlight">
          <thead>
          <tr>
            <th>Lokation</th>
            <th>Reviews</th>
            <th><%= t(:review_average) %></th>
            <!-- <th>Tweets</th>
     <th>Tweets neu</th>
     <th>Followers<a href="#" rel="popover" title="Twitter Tip" data-content="Lorem ipsum"><i class="icon-list icon-question-sign"></i></a>	</th>
     <th>Listed<a href="#" rel="popover" title="Twitter Tip" data-content="Lorem ipsum erm&ouml;glicht seinen Nutzern eine Lokation zu Empfehlen. Diese Empfehlungen nennen sich 'Foursquare Tip'"><i class="icon-list icon-question-sign"></i></a>	</th>
        <th>Fb gefällt mir<a href="#" rel="popover" title="Facebook Tip" data-content="Lorem ipsum erm&ouml;glicht seinen Nutzern eine Lokation zu Empfehlen. Diese Empfehlungen nennen sich 'Foursquare Tip'"><i class="icon-list icon-question-sign"></i></a>	</th>
        <th>Fb gefällt mir neu<a href="#" rel="popover" title="Facebook Tip" data-content="Lorem ipsum erm&ouml;glicht seinen Nutzern eine Lokation zu Empfehlen. Diese Empfehlungen nennen sich 'Foursquare Tip'"><i class="icon-list icon-question-sign"></i></a>	</th> -->
            <th>Foursquare Users</th>
            <th>Foursquare Checkins</th>
            <th>Foursquare
              Tip<a href="#" rel="popover" title="Foursquare Tip" data-content="Foursquare allows to recommend locations as a 'Tip'."></i></a>                    
            </th>
            <!--&lt;!&ndash; <th>Mentions</th>-->
            <!--  <th>Mentions neu</th>
         <th>Blog Beiträge</th>
         <th>Blog Beiträge neu</th> -->
          </tr>
          </thead>

          <tbody>
          <tr>
            <% unless @aggregate_result.nil? %>
                <td><%= @aggregate_result.organization.name %></td>
                <td><%= @aggregate_result.reviews %></td>
                <td><%= @aggregate_result.review_avg %></td>
                <td><%= @aggregate_result.fs_users_count %>
                <td><%= @aggregate_result.fs_checkins_count %>
                <td><%= @aggregate_result.fs_tip_count %>
            <% end %>
          </tr>
          </tbody>

        </table>

        <br/>
      </div>
      <h3><%= t(:competitor_results) %></h3>

      <table class="table table-striped table-bordered table-highlight">
        <thead>
        <tr>
          <th>Lokation</th>
          <th>Reviews</th>
          <th><%= t(:review_average) %></th>
        </tr>
        </thead>
        <tbody>
        <% unless @aggregate_results2.nil? %>
            <% @aggregate_results2.each do |aggregate_result2| %>
                <tr>
                  <td>
                    <a href="/reviews/<%= aggregate_result2.organization.id %>"><%= aggregate_result2.organization.name %></a>
                  </td>
                  <td><%= aggregate_result2.reviews %></td>
                  <td><%= aggregate_result2.review_avg %></td>
            <% end %>
        <% end %>

        </tr>
        </tbody>
      </table>


      <br/>
    </div>
  </div>

  <script type="text/javascript">
      $("a[rel=popover]")
              .popover()
              .click(function (e) {
                  e.preventDefault()
              })
  </script>

app/views/aggregate_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Organization:</b>
  <%= @aggregate_result.organization_id %>
</p>

<p>
  <b>Reviews:</b>
  <%= @aggregate_result.reviews %>
</p>

<p>
  <b>Review avg:</b>
  <%= @aggregate_result.review_avg %>
</p>

<p>
  <b>Tweets:</b>
  <%= @aggregate_result.tweets %>
</p>

<p>
  <b>Tweets new:</b>
  <%= @aggregate_result.tweets_new %>
</p>

<p>
  <b>Fb likes:</b>
  <%= @aggregate_result.fb_likes %>
</p>

<p>
  <b>Fb likes new:</b>
  <%= @aggregate_result.fb_likes_new %>
</p>



<%= link_to 'Edit', edit_aggregate_result_path(@aggregate_result) %> |
<%= link_to 'Back', aggregate_results_path %>